language: php

sudo: false

cache:
  directories:
        - $HOME/.composer/cache

php:
  - '7.3'
  - '7.4'
  - '8.0'
  - nightly

before_install:
  - sudo apt-get update
  - sudo apt-get install -y ant

before_script:
 - phpunit --version
 - travis_retry composer install --no-dev

script:
  - ant travis
